# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_handler', '0003_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinetask',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
