# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_handler', '0004_auto_20160417_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='latest_event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_handler.RecurringEvent'),
        ),
        migrations.AlterField(
            model_name='deadlinetask',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
