# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_handler', '0005_auto_20160417_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtask',
            name='last_occured',
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
