# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_handler', '0006_auto_20160417_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringevent',
            old_name='time_since_last',
            new_name='started_time',
        ),
    ]
