# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_handler', '0007_auto_20160417_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinetask',
            name='task_type',
            field=models.CharField(default='deadline', max_length=120),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='task_type',
            field=models.CharField(default='recurring', max_length=120),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='completed_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='started_time',
            field=models.DateTimeField(),
        ),
    ]
