# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_handler', '0009_notes_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(),
        ),
    ]
